### ISSUE TITLE
Mutation arguments

### ISSUE THREAD

**Issue by alkskjelett** [axtiva/flexible-graphql-bundle#13]
It is not clear how to determine whether arguments were not passed to the mutation or were passed as null. When mutation is an editing one, i create form with values from database, then i set mutation data to form via submit method and not passed values that null are overwrite normal data form.

Example:

```
type Mutation {
   editAuthor(
        id: ID!
        firstname: String
        lastname: String
        patronymic: String
        books: Int
    ): Author
}

type Author {
    id: ID!
    firstname: String!
    lastname: String!
    patronymic: String
    books: Int
}
```

if i execute this mutation:
```
mutation editAuthor {
    editAuthor(
        id: 1
        books: 5
    )
   {
       id
   }
}
```
i get these values in args variable, in __invoke method, in EditAithorResolver

actual args value:
```
[
    'id' => 1,
    'firstname' => null,
    'lastname' => null,
    'patronymic' => null,
    'books' => 5
]
```
i need:
```
[
    'id'  => 1,
    'books' => 5
]
```

if i exucute this mutation:
```
mutation editAuthor {
    editAuthor(
        id: 1
        firstname: null,
        lastname: null,
        patronymic: null,
        books: 5
    )
   {
       id
   }
}
```

actual args value:
```
[
    'id' => 1,
    'firstname' => null,
    'lastname' => null,
    'patronymic' => null,
    'books' => 5
]
```
i need:
```
[
    'id' => 1,
    'firstname' => null,
    'lastname' => null,
    'patronymic' => null,
    'books' => 5
]
```

How to filter in the resolver args the values ​​passed to the mutation as null, from those passed to the mutation at all?

**Comment by bpteam** [comment]
Hello [alkskjelett](https://github.com/alkskjelett)! 

If you pass default value to some args like `books: Int = 5`

```graphql
type Mutation {
   editAuthor(
        id: ID!
        firstname: String
        lastname: String
        patronymic: String
        books: Int = 5
    ): Author
}
```
It means if books not provided, than books value equals to 5

And `patronymic: String` it means `patronymic` is null by default

if you need

```php
[
    'id'  => 1,
    'books' => 5
]
```

than you need to remap args to new variable w/o empty values.

Thank you for your interest to the library!

I will close this issue. Feel free to reopen if I do not answer your question.
